// <auto-generated />
using Lexica.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lexica.EF.Migrations
{
    [DbContext(typeof(LexicaContext))]
    [Migration("20210410111737_initialize-db")]
    partial class initializedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Lexica.EF.Models.LearningHistoryTable", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_correct");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("namespace");

                    b.Property<string>("ProperAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("proper_answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question_type");

                    b.HasKey("OperationId");

                    b.ToTable("learning_history", "modes");
                });
#pragma warning restore 612, 618
        }
    }
}
